### ISSUE TITLE
Fix flickering when loading snippets

### ISSUE THREAD

**Issue by glogiotatidis** [mozmar/snippets#85]
Gif explains it:

![output](https://cloud.githubusercontent.com/assets/584352/18160268/5226c8b8-7035-11e6-9808-36557f1f09d7.gif)

**Comment by glogiotatidis** [comment]
Hey @ScottDowne do you have any ideas and / or time to look at this?

**Comment by ScottDowne** [comment]
I do. Looking now.

**Comment by ScottDowne** [comment]
@glogiotatidis This is a new issue, correct?

**Comment by glogiotatidis** [comment]
No, I's was sparse on the issue description:

The issue is not new, it's been around for quite some time but it's very annoying and give a broken feeling to users. If we can make it so the insertion of the snippet does not move the search bar and the log it would be fantastic!

**Comment by ScottDowne** [comment]
I don't think it has to do with the snippet, but with the layout of the rest of the page.

The `#topSection` container wants to be vertically centered. When the snippet is injected, it potentially (usually) changes the height of `#topSection`.

This causes everything to become re vertically centered.

I'm not sure of a recommended fix, yet.

**Comment by ScottDowne** [comment]
The one area I want to explore more is the default snippets don't have this issue on load, but they are definitely taking up space, and thus should be causing this issue.

Looks like `#snippets` has a `min-height: calc(15/12 * 3em);` so anything that has a higher height than that, causes this issue.

**Comment by glogiotatidis** [comment]
IC makes much sense. I notice very small flickering on the default snippets too but maybe that's also a combination of available system fonts etc.

We can pull request against Gecko I change the about:home CSS if that's helpful to fix the issue.

**Comment by ScottDowne** [comment]
We might need to do changes in about:home CSS, not sure though.

Some ideas I have are:

1. Center the icon and search bar as if the snippet wasn't there. This would eliminate the stutter, but it would mean everything is a little lower, by about half the snippet's height. Think of it as if the snippet was floating weightlessly under the search bar. I can prototype this if we want, and we can compare. It would be a pretty un disruptive change in about:home CSS. Older browsers wouldn't have this fix.
2. Use height transitions. This one is kinda meh, but would be better than what we have. I just don't like height transitions, as they are kinda hacky.
3. Delay the loading of the icon and search, until the snippet is loaded. I feel like this might be a no option, because it has potential to introduce cases where bugs could stop the page from loading. Too many moving parts.
4. Somehow render the initial page with the snippet already loaded. No idea how to do this, but would be ideal if possible.

**Comment by ScottDowne** [comment]
I would investigate options 4 and 1.

**Comment by glogiotatidis** [comment]
I learn that we'll have a go / no-go decision on Activity Stream early next month. If we're going with Activity stream snippets will change altogether so it's not worth it to fix this. Otherwise we'll revisit. I'll update with more news as they come

**Comment by ScottDowne** [comment]
Makes sense. Thanks for the update.

**Comment by glogiotatidis** [comment]
We will be going forward with activity stream so it's not worth spending time on this now. Thanks for your insights and work @ScottDowne
